apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: convoy
  labels:
    app: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: load-generator
          image: ${LOAD_GENERATOR_IMAGE}
          ports:
            - containerPort: 8081
          env:
            - name: INGESTION_SERVICE_URL
              value: http://ingestion-service.convoy.svc.cluster.local:8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 768Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 20
