server:
  port: 8081

logging:
  file:
    name: ${LOG_FILE_NAME:logs/load-generator.log}
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
      total-size-cap: 100MB

spring:
  application:
    name: load-generator
  jackson:
    property-naming-strategy: SNAKE_CASE

app:
  target:
    url: ${INGESTION_SERVICE_URL:http://ingestion-service.convoy.svc.cluster.local:8080}
  simulation:
    vehicle-count: ${VEHICLE_COUNT:10000}
    min-requests-per-second: ${MIN_RPS:500}
    max-requests-per-second: ${MAX_RPS:1000}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
